# Generated by Django 2.2.12 on 2020-04-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200415_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=128)),
                ('dob', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=12)),
                ('Email', models.EmailField(blank=True, max_length=70)),
                ('Category', models.CharField(choices=[('B', 'Family Tours'), ('R', 'Religious Tours'), ('S', 'Solo Trips'), ('A', 'Adventure Trips')], max_length=128)),
                ('No_of_Days', models.IntegerField()),
                ('No_of_Childrens', models.IntegerField()),
                ('No_of_Adults', models.IntegerField()),
                ('Enquiry_message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
