# Generated by Django 2.2.12 on 2020-04-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200416_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packagess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=200)),
                ('packages', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('information', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
